### ISSUE TITLE
Fail to create a new tab

### ISSUE THREAD

**Issue by tyanyuy3125** [Jieck2002/smartab#1]
platform: Microsoft Edge
the debugger of the F12 Developer Tools threw a exception called "SCRIPT16389: Unspecified error" on line 257 of `index.html` inside your project. I'm wondering if that is a compatibility issue or permission some thing goes wrong.
Thx.
And..Well, long time no see...

**Comment by Jethro2002** [comment]
emmm，说中文，我英语太渣。

制作smartab的环境是在iis服务端下，但是通过文件夹目录直接打开也可以正常使用。

也许f12会出现错误提示，可能不会影响正常使用吧？是吗？

如果影响，请给予我回复！

谢谢对我项目的支持！：）

**Comment by junzhengca** [comment]
This is a Microsoft Edge bug #8816771.
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8816771/

Nothing wrong with your code.
*You can close this issue*

**Comment by Jethro2002** [comment]
OK,thanks
